export const data = [
  {
    "Contact ID": "J1BygjiNRs2cRF9iTBpo",
    Stage: "Awaiting Approval",
    "First Name": "Ramona",
    "Last Name": "Tabor",
    Email: "Ramona.Tabor@ingrammarine.com",
    Country: "US",
    Department: "Ingram dispatch",
    "Supervisor Name": "Teresa Chambers",
    "Supervisor Email": "Teresa.chambers@ingrambarge.com",
    "Currently Studying Level": "",
    "Stackoverflow URL": "",
    Program: "Web Development",
    "Target Certification": "Full-Stack Engineer",
    "Program Style": "",
    "Enrollment Type": "Part-Time",
    "Expected Start Date": "",
    "Expected End Date": "",
    "Current Badge Count": "",
    "Create Date": "2022-07-29T09:50:03.801Z",
    "Last Activity Date": "2022-07-29T10:01:55.883Z",
    "Work Experience Industries": ["Food Service"],
    "College Degree Area": "Chef de Cuisine",
    "Years Work Experience": 45,
    "Education Level": "High School",
    "Researching on the Web Level": "3",
    "Attention Span Level": "1",
    "Finishing Level": "5",
    "Starting Level": "1",
    "Learning New Software/Programs": "3",
    "Resilience Level": "4",
    "Existing Programming Skills": "None",
    Diligence: "5",
    "New Ideas Level": "1",
    "Flexibility Level": "1",
    "Overcoming Level": "5",
    "Using Computers Level": "4",
    "Stamina Level": "5",
    "Computer Networking Level": "4",
    "Technical Training Level": "",
    "Computer Hardware Level": "3",
    "Orientation confidence ": "",
    "Interests Change Level": "1",
  },
  {
    "Contact ID": "nqHceLcqsvla3v9FrdFb",
    Stage: "Inviting to Orientation",
    "First Name": "Testy",
    "Last Name": "Tester",
    Email: "sommardahl+ingram9@gmail.com",
    Country: "US",
    Department: "Testing",
    "Supervisor Name": "Testing",
    "Supervisor Email": "Testing",
    "Currently Studying Level": "",
    "Stackoverflow URL": "",
    Program: "Web Development",
    "Target Certification": "Full-Stack Engineer",
    "Program Style": "",
    "Enrollment Type": "Part-Time",
    "Expected Start Date": "",
    "Expected End Date": "",
    "Current Badge Count": "",
    "Create Date": "2022-07-28T20:27:54.700Z",
    "Last Activity Date": "2022-07-28T21:57:59.875Z",
    "Work Experience Industries": ["Hospitality"],
    "College Degree Area": "",
    "Years Work Experience": 4,
    "Education Level": "Associates Degree",
    "Researching on the Web Level": "5",
    "Attention Span Level": "4",
    "Finishing Level": "4",
    "Starting Level": "4",
    "Learning New Software/Programs": "3",
    "Resilience Level": "4",
    "Existing Programming Skills": "Lots",
    Diligence: "5",
    "New Ideas Level": "5",
    "Flexibility Level": "5",
    "Overcoming Level": "3",
    "Using Computers Level": "4",
    "Stamina Level": "5",
    "Computer Networking Level": "4",
    "Technical Training Level": ["Coding Bootcamp/School"],
    "Computer Hardware Level": "4",
    "Orientation confidence ": "",
    "Interests Change Level": "4",
  },
  {
    "Contact ID": "mwwraZmS1KIV1CDU4sm8",
    Stage: "Inviting to Orientation",
    "First Name": "Charles",
    "Last Name": "Simmons",
    Email: "ccsim1@bellsouth.net",
    Country: "US",
    Department: "Marine",
    "Supervisor Name": "Jeff Conner",
    "Supervisor Email": "jeff.conner@ingrambarge.com",
    "Currently Studying Level": "",
    "Stackoverflow URL": "",
    Program: "",
    "Target Certification": "Full-Stack Engineer",
    "Program Style": "",
    "Enrollment Type": "Part-Time",
    "Expected Start Date": "",
    "Expected End Date": "",
    "Current Badge Count": "",
    "Create Date": "2022-07-28T16:17:10.891Z",
    "Last Activity Date": "2022-07-28T16:24:14.324Z",
    "Work Experience Industries": [
      "Logistics",
      "Manufacturing",
      "Construction",
      "Retail",
    ],
    "College Degree Area": "Mechanical Engineering",
    "Years Work Experience": 30,
    "Education Level": "Some College",
    "Researching on the Web Level": "3",
    "Attention Span Level": "1",
    "Finishing Level": "4",
    "Starting Level": "1",
    "Learning New Software/Programs": "3",
    "Resilience Level": "5",
    "Existing Programming Skills": "None",
    Diligence: "4",
    "New Ideas Level": "2",
    "Flexibility Level": "1",
    "Overcoming Level": "5",
    "Using Computers Level": "3",
    "Stamina Level": "5",
    "Computer Networking Level": "1",
    "Technical Training Level": ["Self-Taught", "On-the-job Training"],
    "Computer Hardware Level": "1",
    "Orientation confidence ": "",
    "Interests Change Level": "1",
  },
  {
    "Contact ID": "LNBCfRjxWMAn0UlwVq4S",
    Stage: "Inviting to Orientation",
    "First Name": "Thomas",
    "Last Name": "Pool",
    Email: "tpool58@gmail.com",
    Country: "US",
    Department: "Wheelhouse",
    "Supervisor Name": "David Edgin",
    "Supervisor Email": "David.Edgin@ingrambarge.com",
    "Currently Studying Level": "",
    "Stackoverflow URL": "",
    Program: "",
    "Target Certification": "Full-Stack Engineer",
    "Program Style": "",
    "Enrollment Type": "Part-Time",
    "Expected Start Date": "",
    "Expected End Date": "",
    "Current Badge Count": "",
    "Create Date": "2022-07-27T22:09:11.947Z",
    "Last Activity Date": "2022-07-27T22:11:46.912Z",
    "Work Experience Industries": ["Hospitality", "Manufacturing"],
    "College Degree Area": "BS Chemical Engineering",
    "Years Work Experience": 7,
    "Education Level": "Some College",
    "Researching on the Web Level": "4",
    "Attention Span Level": "4",
    "Finishing Level": "5",
    "Starting Level": "2",
    "Learning New Software/Programs": "4",
    "Resilience Level": "5",
    "Existing Programming Skills": "None",
    Diligence: "4",
    "New Ideas Level": "3",
    "Flexibility Level": "3",
    "Overcoming Level": "5",
    "Using Computers Level": "4",
    "Stamina Level": "4",
    "Computer Networking Level": "3",
    "Technical Training Level": ["On-the-job Training"],
    "Computer Hardware Level": "3",
    "Orientation confidence ": "",
    "Interests Change Level": "2",
  },
  {
    "Contact ID": "n4cvPTWwTe5ayKpPmtaY",
    Stage: "Invited to Schedule Kickoff",
    Approval: "Pending",
    "First Name": "Michael",
    "Last Name": "Hewitt",
    Email: "michaelhewitt89@yahoo.com",
    Country: "US",
    Department: "Marine ",
    "Supervisor Name": "Len O'Connor",
    "Supervisor Email": "Len.oconnor@ingrammarine.com",
    "Currently Studying Level": "",
    "Stackoverflow URL": "",
    Program: "Web Development",
    "Target Certification": "Full-Stack Engineer",
    "Program Style": "Self-Paced",
    "Enrollment Type": "Part-Time",
    "Expected Start Date": "",
    "Expected End Date": "",
    "Current Badge Count": "",
    "Create Date": "2022-07-27T21:05:48.443Z",
    "Last Activity Date": "2022-07-27T22:23:35.732Z",
    "Work Experience Industries": ["Construction"],
    "College Degree Area": "NA",
    "Years Work Experience": 7,
    "Education Level": "High School",
    "Researching on the Web Level": "5",
    "Attention Span Level": "1",
    "Finishing Level": "4",
    "Starting Level": "2",
    "Learning New Software/Programs": "5",
    "Resilience Level": "4",
    "Existing Programming Skills": "None",
    Diligence: "4",
    "New Ideas Level": "1",
    "Flexibility Level": "2",
    "Overcoming Level": "5",
    "Using Computers Level": "4",
    "Stamina Level": "4",
    "Computer Networking Level": "4",
    "Technical Training Level": "",
    "Computer Hardware Level": "4",
    "Orientation confidence ": "",
    "Interests Change Level": "2",
  },
  {
    "Contact ID": "6ZHw6FZBvIX0pYgtp4uX",
    Stage: "Inviting to Orientation",
    "First Name": "Nicholas",
    "Last Name": "Vittitoe",
    Email: "nicholas.vittitoe@ingrammarine.com",
    Country: "US",
    Department: "Senior deckhand",
    "Supervisor Name": "Jeff conner",
    "Supervisor Email": "Jeff.conner@ingrambarge.com",
    "Currently Studying Level": "",
    "Stackoverflow URL": "",
    Program: "",
    "Target Certification": "Full-Stack Engineer",
    "Program Style": "",
    "Enrollment Type": "Part-Time",
    "Expected Start Date": "",
    "Expected End Date": "",
    "Current Badge Count": "",
    "Create Date": "2022-07-27T01:44:09.425Z",
    "Last Activity Date": "2022-07-27T01:48:03.182Z",
    "Work Experience Industries": "",
    "College Degree Area": "",
    "Years Work Experience": "",
    "Education Level": "",
    "Researching on the Web Level": "",
    "Attention Span Level": "",
    "Finishing Level": "",
    "Starting Level": "",
    "Learning New Software/Programs": "",
    "Resilience Level": "",
    "Existing Programming Skills": "",
    Diligence: "",
    "New Ideas Level": "",
    "Flexibility Level": "",
    "Overcoming Level": "",
    "Using Computers Level": "",
    "Stamina Level": "",
    "Computer Networking Level": "",
    "Technical Training Level": "",
    "Computer Hardware Level": "",
    "Orientation confidence ": "",
    "Interests Change Level": "",
  },
  {
    "Contact ID": "Rcr03bCYkvnBsLqCDet8",
    Stage: "Ready for Kickoff",
    Approval: "Pending",
    "First Name": "Clarence",
    "Last Name": "Sheets",
    Email: "clarence.sheets@ingrammarine.com",
    Country: "US",
    Department: "Marine Deck",
    "Supervisor Name": "David Edgin",
    "Supervisor Email": "David.Edgin@ingrambarge,com",
    "Currently Studying Level": "",
    "Stackoverflow URL":
      "https://stackoverflow.com/users/19629395/clarence-sheets",
    Program: "Web Development",
    "Target Certification": "Full-Stack Engineer",
    "Program Style": "Self-Paced",
    "Enrollment Type": "Part-Time",
    "Expected Start Date": "2022-08-01",
    "Expected End Date": "2024-02-01",
    "Current Badge Count": "",
    "Create Date": "2022-07-26T14:19:05.367Z",
    "Last Activity Date": "2022-07-26T21:26:50.716Z",
    "Work Experience Industries": ["Food Service", "Manufacturing", "Other"],
    "College Degree Area": "AAS in Marine Tech",
    "Years Work Experience": 18,
    "Education Level": "Associates Degree",
    "Researching on the Web Level": "4",
    "Attention Span Level": "2",
    "Finishing Level": "3",
    "Starting Level": "2",
    "Learning New Software/Programs": "5",
    "Resilience Level": "5",
    "Existing Programming Skills": "None",
    Diligence: "5",
    "New Ideas Level": "3",
    "Flexibility Level": "3",
    "Overcoming Level": "4",
    "Using Computers Level": "3",
    "Stamina Level": "5",
    "Computer Networking Level": "1",
    "Technical Training Level": ["Self-Taught"],
    "Computer Hardware Level": "2",
    "Orientation confidence ": "",
    "Interests Change Level": "2",
  },
  {
    "Contact ID": "icMGEz9GGb1mIWRF7epn",
    Stage: "Orientation Started",
    "First Name": "Albert",
    "Last Name": "Henderson",
    Email: "albert.henderson@ingrammarine.com",
    Country: "US",
    Department: "Off shore",
    "Supervisor Name": "William sanders ",
    "Supervisor Email": "William.sanders@ingrammarine.com",
    "Currently Studying Level": "",
    "Stackoverflow URL": "",
    Program: "",
    "Target Certification": "Full-Stack Engineer",
    "Program Style": "",
    "Enrollment Type": "Part-Time",
    "Expected Start Date": "",
    "Expected End Date": "",
    "Current Badge Count": "",
    "Create Date": "2022-07-25T23:15:15.292Z",
    "Last Activity Date": "2022-07-26T22:23:26.642Z",
    "Work Experience Industries": "",
    "College Degree Area": "",
    "Years Work Experience": "",
    "Education Level": "",
    "Researching on the Web Level": "",
    "Attention Span Level": "",
    "Finishing Level": "",
    "Starting Level": "",
    "Learning New Software/Programs": "",
    "Resilience Level": "",
    "Existing Programming Skills": "",
    Diligence: "",
    "New Ideas Level": "",
    "Flexibility Level": "",
    "Overcoming Level": "",
    "Using Computers Level": "",
    "Stamina Level": "",
    "Computer Networking Level": "",
    "Technical Training Level": "",
    "Computer Hardware Level": "",
    "Orientation confidence ": "",
    "Interests Change Level": "",
  },
  {
    "Contact ID": "3BaP2Uu0euC4dgr7Xw32",
    Stage: "Inviting to Orientation",
    "First Name": "Taylor",
    "Last Name": "Cuccia",
    Email: "taylor.cuccia@ingrammarine.com",
    Country: "US",
    Department: "Senior lead deckhand ",
    "Supervisor Name": "Jeff conners ",
    "Supervisor Email": "Jeff.conners@ingrammarine.com ",
    "Currently Studying Level": "",
    "Stackoverflow URL": "",
    Program: "",
    "Target Certification": "Full-Stack Engineer",
    "Program Style": "",
    "Enrollment Type": "Part-Time",
    "Expected Start Date": "",
    "Expected End Date": "",
    "Current Badge Count": "",
    "Create Date": "2022-07-25T19:27:08.587Z",
    "Last Activity Date": "2022-07-25T19:29:23.836Z",
    "Work Experience Industries": ["Other"],
    "College Degree Area": "",
    "Years Work Experience": 9,
    "Education Level": "High School",
    "Researching on the Web Level": "4",
    "Attention Span Level": "1",
    "Finishing Level": "5",
    "Starting Level": "2",
    "Learning New Software/Programs": "5",
    "Resilience Level": "5",
    "Existing Programming Skills": "None",
    Diligence: "5",
    "New Ideas Level": "2",
    "Flexibility Level": "1",
    "Overcoming Level": "5",
    "Using Computers Level": "4",
    "Stamina Level": "5",
    "Computer Networking Level": "4",
    "Technical Training Level": ["Trade School", "On-the-job Training"],
    "Computer Hardware Level": "3",
    "Orientation confidence ": "",
    "Interests Change Level": "1",
  },
  {
    "Contact ID": "Ybow8XBEQARdrpeFegtI",
    Stage: "Invited to Schedule Kickoff",
    Approval: "Pending",
    "First Name": "Robert",
    "Last Name": "Fleenor",
    Email: "Robert.fleenor@ingrammarine.com",
    Country: "US",
    Department: "Marine",
    "Supervisor Name": "Damon Daigle",
    "Supervisor Email": "damon.daigle@ingrammarine.com",
    "Currently Studying Level": "",
    "Stackoverflow URL": "",
    Program: "Web Development",
    "Target Certification": "Full-Stack Engineer",
    "Program Style": "Self-Paced",
    "Enrollment Type": "Part-Time",
    "Expected Start Date": "",
    "Expected End Date": "",
    "Current Badge Count": "",
    "Create Date": "2022-07-25T10:20:42.123Z",
    "Last Activity Date": "2022-07-28T11:14:56.887Z",
    "Work Experience Industries": ["Food Service", "Construction", "Other"],
    "College Degree Area": "Architecture mechanical drafting",
    "Years Work Experience": 28,
    "Education Level": "Some College",
    "Researching on the Web Level": "4",
    "Attention Span Level": "1",
    "Finishing Level": "4",
    "Starting Level": "2",
    "Learning New Software/Programs": "3",
    "Resilience Level": "4",
    "Existing Programming Skills": "None",
    Diligence: "5",
    "New Ideas Level": "2",
    "Flexibility Level": "1",
    "Overcoming Level": "5",
    "Using Computers Level": "4",
    "Stamina Level": "2",
    "Computer Networking Level": "2",
    "Technical Training Level": [
      "Trade School",
      "Self-Taught",
      "On-the-job Training",
    ],
    "Computer Hardware Level": "4",
    "Orientation confidence ": "",
    "Interests Change Level": "2",
  },
  {
    "Contact ID": "ejARwN1pesmOyMxlxkzh",
    Stage: "Ready for Kickoff",
    Approval: "Pending",
    "First Name": "Nathan",
    "Last Name": "Olmstead",
    Email: "nathan.olmstead@ingrammarine.com",
    Country: "US",
    Department: "Marine",
    "Supervisor Name": "LouAnn Stokesberry ",
    "Supervisor Email": "LouAnn.Stokesberry@ingrambarge.com",
    "Currently Studying Level": "",
    "Stackoverflow URL": "",
    Program: "Web Development",
    "Target Certification": "Full-Stack Engineer",
    "Program Style": "Self-Paced",
    "Enrollment Type": "Part-Time",
    "Expected Start Date": "",
    "Expected End Date": "",
    "Current Badge Count": "",
    "Create Date": "2022-07-23T05:09:18.966Z",
    "Last Activity Date": "2022-07-23T15:29:35.927Z",
    "Work Experience Industries": ["Construction", "Agriculture", "Retail"],
    "College Degree Area": "Ingram Barge Company",
    "Years Work Experience": 10,
    "Education Level": "High School",
    "Researching on the Web Level": "3",
    "Attention Span Level": "4",
    "Finishing Level": "4",
    "Starting Level": "2",
    "Learning New Software/Programs": "1",
    "Resilience Level": "5",
    "Existing Programming Skills": "None",
    Diligence: "4",
    "New Ideas Level": "2",
    "Flexibility Level": "2",
    "Overcoming Level": "4",
    "Using Computers Level": "3",
    "Stamina Level": "5",
    "Computer Networking Level": "1",
    "Technical Training Level": [],
    "Computer Hardware Level": "1",
    "Orientation confidence ": "",
    "Interests Change Level": "4",
  },
  {
    "Contact ID": "8MvwQJwy56wKF02g6EIW",
    Stage: "Invited to Schedule Kickoff",
    Approval: "Pending",
    "First Name": "Jessie",
    "Last Name": "Woodard",
    Email: "jessie.woodard@ingrammarine.com",
    Country: "US",
    Department: "Marine",
    "Supervisor Name": "Jeff Conors",
    "Supervisor Email": "Jeff.conors@ingammarine.com",
    "Currently Studying Level": "",
    "Stackoverflow URL": "",
    Program: "Web Development",
    "Target Certification": "Full-Stack Engineer",
    "Program Style": "Self-Paced",
    "Enrollment Type": "Part-Time",
    "Expected Start Date": "",
    "Expected End Date": "",
    "Current Badge Count": "",
    "Create Date": "2022-07-22T21:53:13.407Z",
    "Last Activity Date": "2022-07-22T22:16:37.010Z",
    "Work Experience Industries": [
      "Hospitality",
      "Food Service",
      "Construction",
    ],
    "College Degree Area": "",
    "Years Work Experience": 6,
    "Education Level": "High School",
    "Researching on the Web Level": "5",
    "Attention Span Level": "2",
    "Finishing Level": "5",
    "Starting Level": "2",
    "Learning New Software/Programs": "4",
    "Resilience Level": "5",
    "Existing Programming Skills": "None",
    Diligence: "5",
    "New Ideas Level": "3",
    "Flexibility Level": "1",
    "Overcoming Level": "5",
    "Using Computers Level": "4",
    "Stamina Level": "5",
    "Computer Networking Level": "3",
    "Technical Training Level": ["On-the-job Training"],
    "Computer Hardware Level": "3",
    "Orientation confidence ": "",
    "Interests Change Level": "2",
  },
  {
    "Contact ID": "OtcmD9CXpT4qEoXu7Ajo",
    Stage: "Ready for Kickoff",
    Approval: "Pending",
    "First Name": "Anthony",
    "Last Name": "Ellis",
    Email: "anthony.ellis@ingrammarine.com",
    Country: "US",
    Department: "Cook ",
    "Supervisor Name": "Thomas Cagle",
    "Supervisor Email": "Thomas.cagle@ingrammarine.com",
    "Currently Studying Level": 1,
    "Stackoverflow URL": "",
    Program: "Web Development",
    "Target Certification": "Full-Stack Engineer",
    "Program Style": "Self-Paced",
    "Enrollment Type": "Part-Time",
    "Expected Start Date": "2022-08-22",
    "Expected End Date": "2024-02-22",
    "Current Badge Count": "",
    "Create Date": "2022-07-22T21:36:52.936Z",
    "Last Activity Date": "2022-07-22T21:59:56.918Z",
    "Work Experience Industries": [
      "Food Service",
      "Construction",
      "Hospitality",
    ],
    "College Degree Area": "Hotel and Restaurant management and Culinary ",
    "Years Work Experience": 17,
    "Education Level": "Some College",
    "Researching on the Web Level": "4",
    "Attention Span Level": "1",
    "Finishing Level": "5",
    "Starting Level": "1",
    "Learning New Software/Programs": "4",
    "Resilience Level": "5",
    "Existing Programming Skills": "None",
    Diligence: "3",
    "New Ideas Level": "1",
    "Flexibility Level": "3",
    "Overcoming Level": "5",
    "Using Computers Level": "5",
    "Stamina Level": "4",
    "Computer Networking Level": "4",
    "Technical Training Level": ["University/College", "Self-Taught"],
    "Computer Hardware Level": "5",
    "Orientation confidence ": "",
    "Interests Change Level": "3",
  },
  {
    "Contact ID": "ZKX0e1HMHPKu3WHZ1Ou0",
    Stage: "Inviting to Orientation",
    "First Name": "ETHAN",
    "Last Name": "CURTIS",
    Email: "ethan.Curtis@ingrammarine.com",
    Country: "US",
    Department: "Deck",
    "Supervisor Name": "Brooke colinger",
    "Supervisor Email": "brooke.colinger@ingrammarine.com",
    "Currently Studying Level": "",
    "Stackoverflow URL": "",
    Program: "",
    "Target Certification": "Full-Stack Engineer",
    "Program Style": "",
    "Enrollment Type": "Part-Time",
    "Expected Start Date": "",
    "Expected End Date": "",
    "Current Badge Count": "",
    "Create Date": "2022-07-22T21:09:35.147Z",
    "Last Activity Date": "2022-07-22T21:11:32.960Z",
    "Work Experience Industries": ["Other"],
    "College Degree Area": "",
    "Years Work Experience": 5,
    "Education Level": "High School",
    "Researching on the Web Level": "5",
    "Attention Span Level": "2",
    "Finishing Level": "3",
    "Starting Level": "2",
    "Learning New Software/Programs": "4",
    "Resilience Level": "3",
    "Existing Programming Skills": "None",
    Diligence: "3",
    "New Ideas Level": "4",
    "Flexibility Level": "2",
    "Overcoming Level": "3",
    "Using Computers Level": "5",
    "Stamina Level": "3",
    "Computer Networking Level": "3",
    "Technical Training Level": ["Self-Taught"],
    "Computer Hardware Level": "5",
    "Orientation confidence ": "",
    "Interests Change Level": "3",
  },
];
